[phases.setup]
nixPkgs = [
  "php83",
  "php83Extensions.pdo",
  "php83Extensions.pdo_mysql",
  "php83Extensions.mbstring",
  "php83Extensions.xml",
  "php83Extensions.curl",
  "php83Extensions.zip",
  "php83Extensions.tokenizer",
  "php83Extensions.fileinfo",
  "php83Extensions.openssl"
]

[phases.install]
cmds = ["composer install --no-dev --optimize-autoloader"]

[phases.build]
cmds = ["npm install && npm run build"]

[start]
cmd = "php artisan migrate --force && php artisan config:cache && php artisan route:cache && php artisan serve --host=0.0.0.0 --port=${PORT:-8000}"